# Site settings
title: Kungl. Bibliotekets tjÃ¤nstemanual
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/service-manual/" # the subpath of your site, e.g. /blog/
url: "http://kungbib.github.io" # the base hostname & protocol for your site
github_username:  kungbib

# Build settings
markdown: kramdown
